"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['chatbot.py']
DATA_FILES = ['static/testdata.yml','static/back.jpg','static/bg.gif','static/close.png','static/flight.gif','static/flight2.gif','static/globe.gif','static/image1.jpg',
'static/image2.png','static/image3.jpg','static/image4.jpg','static/logo.png','static/menu.png']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
